# Featrue Egineering Excercieses With house.csv dataset

In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt

In [93]:
# Read data.
house = pd.read_csv("house.csv", index_col = 0)

In [94]:
# Let's see data.
house.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [95]:
# Let's examine the object types.

house.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 80, dtype: object

In [96]:
# When we look at the explanations, MSSubClass column must be of object type.

house.MSSubClass = house.MSSubClass.astype("str")

In [97]:
house.dtypes

MSSubClass        object
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 80, dtype: object

In [98]:
#Let's check for null expressions in the data set.

house.isnull()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
5,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1457,False,False,False,False,False,True,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
1458,False,False,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1459,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False
1460,False,False,False,False,False,True,False,False,False,False,...,False,True,True,True,False,False,False,False,False,False

In [99]:
# When we examine the explanations, we see that the empty values
# actually indicate that there is no such feature.
df_drop_cols.MasVnrArea = df_drop_cols.MasVnrArea.fillna(0)
df_drop_cols.BsmtQual = df_drop_cols.BsmtQual.fillna("None")
df_drop_cols.BsmtCond = df_drop_cols.BsmtCond.fillna("None")
df_drop_cols.BsmtExposure = df_drop_cols.BsmtExposure.fillna("None")
df_drop_cols.BsmtFinType1 = df_drop_cols.BsmtFinType1.fillna("None")
df_drop_cols.BsmtFinType2 = df_drop_cols.BsmtFinType2.fillna("None")
df_drop_cols.Electrical = df_drop_cols.Electrical.fillna("None")
df_drop_cols.GarageType = df_drop_cols.GarageType.fillna("None")
df_drop_cols.GarageYrBlt = df_drop_cols.GarageYrBlt.fillna(0)
df_drop_cols.GarageFinish = df_drop_cols.GarageFinish.fillna("None")
df_drop_cols.GarageQual = df_drop_cols.GarageQual.fillna("None")
df_drop_cols.GarageCond = df_drop_cols.GarageCond.fillna("None")

In [100]:
# Rebuild the model.

df_drop_cols_dummy = pd.get_dummies(df_drop_cols, drop_first = True)
print(df_drop_cols_dummy.shape)

X = df_drop_cols_dummy.drop("SalePrice", axis = 1)
y = df_drop_cols_dummy["SalePrice"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, 
                                                    random_state = 42)

mdl = LinearRegression()

mdl.fit(X_train, y_train)
ypred = mdl.predict(X_test)

scores = cross_val_score(mdl, X_train, y_train, cv = 10)

results.loc["Fill None"] = [scores.mean(), scores.std(), r2_score(y_test, ypred)]
results

(1460, 252)

                              r2 mean    r2 std   r2 test
Without NA                   0.548538  0.568624  0.373218
Fill None                    0.591975  0.416633  0.642582
Ordinal Value Model          0.598759  0.384457  0.653746
Variance Treshold            0.800696  0.135184  0.866060
Select K-Best                0.699638  0.090742  0.776699
simple imputer and pipeline  0.674101  0.078216  0.748123

In [101]:
# Continue the analysis by copying the data

df_new = df_drop_cols.copy()

In [102]:
cat_cols = [col for col in df_new.columns if df_new[col].dtype == "O"]
cat_cols

['MSSubClass',
 'MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [111]:
#There are ordinal data in the house.csv

def ordinal_category(col):

    """""""""""""""""
    This function detects ordinal data and assigns them values between 0 - 5.
    
    input -> string/ object
    output -> integer

    """""""""""""""""
    
    if col.isin(["Fa", "TA"," Gd", "Ex"]).any():
        return col.replace({"Fa":2, "TA" : 3, "Gd" : 4, "Ex" : 5, "Po" : 1, "None" : 0})
    else:
        return col
df_new[cat_cols] = df_new[cat_cols].apply(ordinal_category)

In [112]:
# Check data.

df_new.GarageCond.value_counts()

GarageCond
3    1326
0      81
2      35
4       9
1       7
5       2
Name: count, dtype: int64

In [113]:
# Check data.

df_new.GarageQual.value_counts()

GarageQual
3    1311
0      81
2      48
4      14
5       3
1       3
Name: count, dtype: int64

In [117]:
from sklearn.impute import SimpleImputer

imputer_num = SimpleImputer(strategy = "mean")

imputer_num.fit(X_train[num_cols])

X_train_num = imputer_num.transform(X_train[num_cols])
X_test_num = imputer_num.transform(X_test[num_cols])


imputer_cat = SimpleImputer(strategy = "most_frequent")

imputer_cat.fit(X_train[cat_cols])

X_train_cat = imputer_cat.transform(X_train[cat_cols])
X_test_cat = imputer_cat.transform(X_test[cat_cols])

encoder = OneHotEncoder(handle_unknown = "ignore", sparse_output = False)

encoder.fit(X_train_cat)
X_train_cat = encoder.transform(X_train_cat)
X_test_cat = encoder.transform(X_test_cat)


X_train_new = np.c_[X_train_num, X_train_cat]
X_test_new = np.c_[X_test_num, X_test_cat]

selector = SelectKBest(f_regression, k = 100)

selector.fit(X_train_new, y_train)

X_train_new = selector.transform(X_train_new)
X_test_new = selector.transform(X_test_new)
print("Train :", r2_score(y_train, ml_pipe.predict(X_train)))
print("Val :", scores.mean())
print("Test :", r2_score(y_test, ypred))

Train : 0.859708748201933
Val : 0.666847937620115
Test : 0.823649643822767

In [116]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeRegressor


# Handles categorical features.
# Fill missing values with the most frequent category.
# convert categorical features into numerical one-hot encoded features.
preprocess_cat = Pipeline([
    ("impute", SimpleImputer(strategy="most_frequent")),
    ("encode", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])


# Handles numerical features.
# Fill missing values with the mean.
# tandardize the numerical features.
preprocess_num = Pipeline([
    ("impute", SimpleImputer(strategy="mean")),
    ("scale", StandardScaler())
])

# Merge the numerical and categorical features.
preprocess = ColumnTransformer([
    ("preprocess_cat", preprocess_cat, cat_cols),
    ("preprocess_num", preprocess_num, num_cols)
])


# Applies the combined preprocessing step.
# Trains a Decision Tree Regressor.
# Selects the top 100 features
ml_pipe = Pipeline([
    ("preprocess", preprocess),
    ("selection", SelectKBest(f_regression, k = 100)),
    ("model", DecisionTreeRegressor(max_depth = 5))
])


#Trains the entire pipeline on the training data.
ml_pipe.fit(X_train , y_train)
ypred = ml_pipe.predict(X_test)
scores = cross_val_score(ml_pipe, X_train, y_train, cv = 10)


results.loc["simple imputer and pipeline"] = [scores.mean(), scores.std(), r2_score(y_test, ypred)]
results

print("Train :", r2_score(y_train, ml_pipe.predict(X_train)))
print("Val :", scores.mean())
print("Test :", r2_score(y_test, ypred))

Train : 0.859708748201933
Val : 0.666847937620115
Test : 0.823649643822767